const swaggerJsdoc = require('swagger-jsdoc');
const swaggerDefinition = {
    // Like the one described here: https://swagger.io/specification/#infoObject
    openapi: '3.0.0',
    info: {
        description: 'Test API with autogenerated swagger doc',
        swagger: '2.0',
        title: 'Node Demo API',
        version: '1.0.0'
    }
    ,
    servers: [
        {
          url: 'http://localhost:3000',
          description: 'Development server'
        }
      ],
    host: 'localhost:3000'
};

const options = {
    swaggerDefinition,
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['api/routes/orders.js']

};

// console.log('test',options)


// console.log( 'test1',options);
// console.log( 'test2',JSON.parse(swaggerDefinition));
const specs = swaggerJsdoc(options);
module.exports = specs;